// Generated by CoffeeScript 1.6.3
(function() {
  var Foursquare, getFoursquareData, session, setSession;

  Foursquare = require("temboo/Library/Foursquare/Users");

  session = null;

  setSession = function(s) {
    return session = s;
  };

  getFoursquareData = function(callback, renderPage) {
    var checkinsByUserChoreo, checkinsByUserInputs, healthy, healthyPoints, netPoints, neutral, unhealthy, unhealthyPoints;
    healthy = [];
    healthyPoints = 0;
    unhealthy = [];
    unhealthyPoints = 0;
    neutral = [];
    netPoints = 0;
    checkinsByUserChoreo = new Foursquare.CheckinsByUser(session);
    checkinsByUserInputs = checkinsByUserChoreo.newInputSet();
    checkinsByUserInputs.setCredential('Foursquare');
    return checkinsByUserChoreo.execute(checkinsByUserInputs, (function(results) {
      var categorizeVenue, checkinsData, data, item, items, pointsClass, _i, _len;
      categorizeVenue = function(venue) {
        if (venue.categories[0]) {
          if (venue.categories[0].name.indexOf("Restaurant") !== -1) {
            unhealthy.push(venue.name);
          }
          if (!(venue.categories[0].name.indexOf("Gym") === -1 && venue.categories[0].name.indexOf("Field") === -1)) {
            healthy.push(venue.name);
          }
          if (!(venue.categories[0].name.indexOf("Restaurant") !== -1 || venue.categories[0].name.indexOf("Gym") !== -1 || venue.categories[0].name.indexOf("Field") !== -1)) {
            return neutral.push(venue.name);
          }
        }
      };
      checkinsData = JSON.parse(results.get_Response());
      items = checkinsData.response.checkins.items;
      for (_i = 0, _len = items.length; _i < _len; _i++) {
        item = items[_i];
        categorizeVenue(item.venue);
      }
      healthyPoints = healthy.length;
      unhealthyPoints = unhealthy.length;
      netPoints = healthyPoints - unhealthyPoints;
      pointsClass = (netPoints >= 0 ? "positive-points" : "negative-points");
      data = {
        checkinsData: checkinsData,
        healthy: healthy,
        healthyPoints: healthyPoints,
        unhealthy: unhealthy,
        unhealthyPoints: unhealthyPoints,
        neutral: neutral,
        netPoints: netPoints,
        pointsClass: pointsClass
      };
      if (renderPage) {
        return callback.render(renderPage, data);
      } else {
        return callback(null, data);
      }
    }), function(error) {
      return console.log(error.type);
    });
  };

  module.exports = {
    setSession: setSession,
    getFoursquareData: getFoursquareData
  };

}).call(this);
