// Generated by CoffeeScript 1.6.3
(function() {
  var cronJob, mailOptions, nodemailer, transport;

  nodemailer = require("nodemailer");

  cronJob = require('cron').CronJob;

  transport = nodemailer.createTransport("SES", {
    AWSAccessKeyID: process.env.AWS_AccessKey,
    AWSSecretKey: process.env.AWS_SecretKey
  });

  mailOptions = {
    from: "cpn585@gmail.com",
    to: "cpn585@gmail.com",
    subject: "Glean Update",
    text: "You are awesome"
  };

  new cronJob('* 1 * * * *', (function() {
    transport.sendMail(mailOptions, function(error, response) {
      if (error) {
        return console.log(error);
      } else {
        return console.log("Message sent " + response.message);
      }
    });
    return transport.close();
  }), null, true, "America/Los_Angeles");

}).call(this);
