// Generated by CoffeeScript 1.6.3
(function() {
  var nodemailer, sendMail;

  nodemailer = require("nodemailer");

  sendMail = function() {
    var mailOptions, transport;
    transport = nodemailer.createTransport("SES", {
      AWSAccessKeyID: process.env.AWS_AccessKey,
      AWSSecretKey: process.env.AWS_SecretKey
    });
    mailOptions = {
      from: "cpn585@gmail.com",
      to: "cpn585@gmail.com",
      subject: "Glean Update",
      text: "You are awesome"
    };
    transport.sendMail(mailOptions, function(error, response) {
      if (error) {
        return console.log(error);
      } else {
        return console.log("Message sent " + response.message);
      }
    });
    return transport.close();
  };

  module.exports = {
    sendMail: sendMail
  };

}).call(this);
