// Generated by CoffeeScript 1.6.3
(function() {
  var RunKeeper, getRunkeeperData;

  RunKeeper = require("temboo/Library/RunKeeper/FitnessActivities");

  getRunkeeperData = function(response, session) {
    var retrieveActivitesChoreo, retrieveActivitesInputs;
    retrieveActivitesChoreo = new RunKeeper.RetrieveActivites(session);
    retrieveActivitesInputs = retrieveActivitesChoreo.newInputSet();
    retrieveActivitesInputs.setCredential("Runkeeper");
    return retrieveActivitesChoreo.execute(retrieveActivitesInputs, (function(results) {
      console.log(JSON.parse(results.get_Response()));
      return response.render("runkeeper");
    }), function(error) {
      console.log(error.type);
      return console.log(error.message);
    });
  };

  module.exports = {
    getRunkeeperData: getRunkeeperData
  };

}).call(this);
