// Generated by CoffeeScript 1.6.3
(function() {
  var RunKeeper, getActivities, getRunkeeperData, session, setSession;

  RunKeeper = require("temboo/Library/RunKeeper/FitnessActivities");

  session = null;

  setSession = function(s) {
    return session = s;
  };

  getRunkeeperData = function(response, session) {
    var retrieveActivitesChoreo, retrieveActivitesInputs;
    retrieveActivitesChoreo = new RunKeeper.RetrieveActivites(session);
    retrieveActivitesInputs = retrieveActivitesChoreo.newInputSet();
    retrieveActivitesInputs.setCredential("Runkeeper");
    return retrieveActivitesChoreo.execute(retrieveActivitesInputs, (function(results) {
      return response.render("runkeeper", JSON.parse(results.get_Response()));
    }), function(error) {
      console.log(error.type);
      return console.log(error.message);
    });
  };

  getActivities = function(callback) {
    var retrieveActivitesChoreo, retrieveActivitesInputs;
    retrieveActivitesChoreo = new RunKeeper.RetrieveActivites(session);
    retrieveActivitesInputs = retrieveActivitesChoreo.newInputSet();
    retrieveActivitesInputs.setCredential("Runkeeper");
    return retrieveActivitesChoreo.execute(retrieveActivitesInputs, (function(results) {
      return callback(null, JSON.parse(results.get_Response()));
    }), function(error) {
      console.log(error.type);
      return console.log(error.message);
    });
  };

  module.exports = {
    setSession: setSession,
    getRunkeeperData: getRunkeeperData,
    getActivities: getActivities
  };

}).call(this);
