// Generated by CoffeeScript 1.6.3
(function() {
  var getRunkeeperData;

  getRunkeeperData = function(response) {
    return response.render("runkeeper");
  };

  module.exports = {
    getRunkeeperData: getRunkeeperData
  };

}).call(this);
