// Generated by CoffeeScript 1.6.3
(function() {
  var ROUTES, app, express, i;

  express = require('express');

  ROUTES = require('./routes');

  app = express();

  app.set('views', __dirname + '/views');

  app.set('view engine', 'ejs');

  app.set('port', process.env.PORT || 8080);

  app.use(express["static"](__dirname + '/public'));

  for (i in ROUTES) {
    app.get(ROUTES[i].path, ROUTES[i].fn);
  }

  app.listen(app.get('port'), function() {
    return console.log("Listening on " + app.get('port'));
  });

}).call(this);
